Feature/mac
NHSDigital/dtos-landing-zone pull request #1
Opened 2024-03-14 10:30 UTC by MacMur85

## Description

A code for initial deployment of Drop 1 resources.

## Context

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-03-18 10:50 UTC, Mahifernando commented
Minor suggestion, do we need "arm-" prefix  for modules names?

2024-03-18 11:01 UTC, Mahifernando requested changes

2024-03-18 11:01 UTC, Mahifernando commented on infrastructure/fnapp.tf
> +  fnapp_count         = var.function_app.fnapp_count
Please consider refactor using collection when needed instead of count of services, this helps for explicit definition of needed service configuration.

2024-03-18 11:01 UTC, Mahifernando commented on infrastructure/fnapp.tf
> +  ]
Similar dependency as baseline, can we use output values to signify storage values are a dependency instead?

2024-03-19 22:33 UTC, MacMur85 commented on infrastructure/appserviceplan.tf
> +  depends_on = [
Dependencies removed, outputs integrated within modules.

2024-03-19 22:33 UTC, MacMur85 commented on infrastructure/variables.tf
> +
Added.

2024-03-19 22:33 UTC, MacMur85 commented on infrastructure/sqlserver.tf
> +  resource_group_name = module.baseline.resource_groups[var.sqlserver.resource_group_index].name
In progress...

2024-03-19 22:34 UTC, MacMur85 commented on infrastructure/fnapp.tf
> +  fnapp_count         = var.function_app.fnapp_count
Roger, in progress...

2024-03-19 22:34 UTC, MacMur85 commented on infrastructure/fnapp.tf
> +  ]
Dependencies removed, outputs integrated within modules.

2024-03-27 23:11 UTC, MacMur85 commented on infrastructure/fnapp.tf
> +  fnapp_count         = var.function_app.fnapp_count
Refactor done, pushed to the repo

2024-03-28 13:18 UTC, Mahifernando approved these changes
All good for merge!

2024-03-28 13:20 UTC, merged