chore: Migrated Cohort Manager to nhs repo
NHSDigital/dtos-landing-zone pull request #12
Opened 2024-05-20 15:24 UTC by alex-clayton-1

## Description

Moved the Cohort Manager over to NHS repo.

## Context

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-05-20 15:40 UTC, Mahifernando commented
Could we move the 'CohortManager' directory into a high-level 'application' directory? This change will help maintain a consistent directory structure, making it easier to target multiple pipeline actions regardless of each application's internal structure.

2024-05-20 15:41 UTC, Mahifernando requested changes
Could we move the 'CohortManager' directory into a high-level 'application' directory? This change will help maintain a consistent directory structure, making it easier to target multiple pipeline actions regardless of each application's internal structure.

2024-05-20 15:43 UTC, Mahifernando reviewed
Please ensure that you have enabled SSH/GPG keys for commit verification. If commits are not signed, the PR will be blocked from merging.

2024-05-20 15:48 UTC, Mahifernando commented on CohortManager/.gitignore
> +# Text Editors
Check if the ignore files in the apps directory are a subset of those in the root directory. If there are overlapping ignore rules, consolidate them into the root-level ignore file while keeping a necessary subset in the apps directory.

2024-05-22 08:19 UTC, Mahifernando approved these changes
Approve for merge 👍 

There are minor changes I can suggest, but the priority is to integrate the code with the main branch so other engineers can start working on it. Any necessary changes or refactoring should be addressed by raising a JIRA ticket in the service planning board.

However, I recommend having a second pair of eyes from the Engineering team review this PR before merging it into the main branch.

2024-05-22 10:45 UTC, andrewmorris43 approved these changes

2024-05-22 12:01 UTC, merged