FEAT: Adding new demographic functions for stubbing the API
NHSDigital/dtos-landing-zone pull request #33
Opened 2024-06-10 07:53 UTC by SamRobinson75684

## Description

this pull request aims to add two functions, which is used as a "getter" and "setter" of the demographic data and one which is used to save and retrieve data from the database pertaining to  demographic data 

## Context

we need to stub what will be calls to an API that we currently do not have access to 

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-06-11 08:21 UTC, alex-clayton-1 requested changes

2024-06-11 08:21 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/Shared/Model/Actions.cs
> +    public const string? Removed = "Removed";
These are const strings so they shouldn't be nullable. Also, for consistency can we stick with all caps for the string values?

2024-06-11 08:21 UTC, alex-clayton-1 commented on application/CohortManager/tests/DemographicDataFunctionTests/DemographicDataFunctionTests.cs
> +
The new tests classes need to go in the root level tests folder

2024-06-11 10:33 UTC, SamRobinson75684 commented on application/CohortManager/tests/DemographicDataFunctionTests/DemographicDataFunctionTests.cs
> +
these tests are contained in the root folder of the tests, and then they are in their own folder the same as all the other tests. See screenshot

![image](https://github.com/NHSDigital/dtos-landing-zone/assets/166817125/33ca41ec-8a22-4b24-9704-88c93418148e)

2024-06-11 10:40 UTC, alex-clayton-1 commented on application/CohortManager/tests/DemographicDataFunctionTests/DemographicDataFunctionTests.cs
> +
What I'm mean is that DemographicDataFunctionTests and DemographicDataServiceTests need to go in the root level tests folder instead of application/CohortManager/tests/

2024-06-11 11:32 UTC, alex-clayton-1 requested changes

2024-06-11 11:32 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/CaasIntegration/processCaasFile/processCaasFile.cs
> +                var DemographicDataInserted = await _checkDemographic.PostDemographicDataAsync(p, Environment.GetEnvironmentVariable("DemographicURI"));
Use camelCase for variables

2024-06-11 11:32 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/DemographicServices/DemographicDataManagementFunction/DemographicDataFunction.cs
> +namespace NHS.demographicServices.DemographicDataManagementFunction.DemographicDataManagementFunction
Use camelCase in namespaces and use file scoped namespaces

2024-06-11 11:32 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/DemographicServices/DemographicDataManagementFunction/DemographicDataManagementFunction.csproj
> +    <ProjectReference Include="..\..\Shared\Data\Data.csproj" />
The Data project reference isn't needed here

2024-06-11 11:32 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/Shared/Model/Participant.cs
> +    public string? participantId { get; set; }
PascalCase for properties

2024-06-11 11:32 UTC, alex-clayton-1 commented on tests/ParticipantManagementServicesTests/RemoveParticipantTests/RemoveParticipantTests.cs
> +    ServiceCollection serviceCollection = new();
Fields should be `private readonly`

2024-06-11 11:32 UTC, alex-clayton-1 commented on tests/ParticipantManagementServicesTests/addParticipantTest/AddParticipantTestClass.cs
> +    private readonly Mock<ICreateParticipant> _CreateParticipant = new();
Use camelCase for private fields

2024-06-11 11:32 UTC, alex-clayton-1 commented on tests/ParticipantManagementServicesTests/updateEligibilityTests/updateEligibilityTests.cs
>          _createResponse.Verify(response => response.CreateHttpResponse(HttpStatusCode.OK, It.IsAny<HttpRequestData>(), ""), Times.Once);
Duplicated lines of code

2024-06-11 11:32 UTC, alex-clayton-1 commented on tests/ParticipantManagementServicesTests/updateEligibilityTests/updateEligibilityTests.cs
>          _createResponse.Verify(response => response.CreateHttpResponse(HttpStatusCode.BadRequest, It.IsAny<HttpRequestData>(), ""), Times.Once);
Duplicated lines of code

2024-06-11 11:32 UTC, alex-clayton-1 commented on tests/ParticipantManagementServicesTests/updateParticipantTests/updateParticipantTests.cs
> -        _callFunction.Verify(call => call.SendPost(It.Is<string>(s => s == "UpdateParticipant"), It.IsAny<string>()), Times.Never());
This seems to be unintentionally reverting a lot of code change. Can you copy this file from main and just make the changes you need, please

2024-06-11 12:02 UTC, SamRobinson75684 commented on tests/ParticipantManagementServicesTests/updateParticipantTests/updateParticipantTests.cs
> -        _callFunction.Verify(call => call.SendPost(It.Is<string>(s => s == "UpdateParticipant"), It.IsAny<string>()), Times.Never());
we don't need all of the set up to create a bad request as we can get one without it all. by removing these lines we just have less to maintain

2024-06-11 12:42 UTC, alex-clayton-1 commented on tests/ParticipantManagementServicesTests/updateParticipantTests/updateParticipantTests.cs
> -        _callFunction.Verify(call => call.SendPost(It.Is<string>(s => s == "UpdateParticipant"), It.IsAny<string>()), Times.Never());
The lines above are verifying that a bad request was created and that update wasn't called which I would argue makes it a more robust test than just verifying a log was made.

2024-06-11 14:01 UTC, SamRobinson75684 commented on application/CohortManager/src/Functions/Shared/Model/Actions.cs
> +    public const string? Removed = "Removed";
that's right, in the test files we have all the values are lower case

2024-06-11 14:13 UTC, alex-clayton-1 requested changes

2024-06-11 14:13 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/screeningDataServices/DemographicDataService/DemographicDataService.cs
> +namespace screeningDataServices
Use PascalCase and file scope for namespace

2024-06-11 14:13 UTC, alex-clayton-1 commented on tests/CaasIntegrationTests/receiveCaasFileTest/ReceiveCaasFileTests.cs
> +            It.IsAny<string>()),
Can this test not also verify that the json is as expected?

2024-06-11 14:13 UTC, alex-clayton-1 commented on tests/ParticipantManagementServicesTests/RemoveParticipantTests/RemoveParticipantTests.cs
> +        Environment.SetEnvironmentVariable("markParticipantAsIneligible", "markParticipantAsIneligible");
Duplicated line of code

2024-06-11 14:17 UTC, SamRobinson75684 commented on application/CohortManager/src/Functions/DemographicServices/DemographicDataManagementFunction/DemographicDataFunction.cs
> +        string requestBody = "";
I would agree with you but Steph has requested we have one method for this in her diagrams

2024-06-11 14:19 UTC, alex-clayton-1 commented on tests/ParticipantManagementServicesTests/updateParticipantTests/updateParticipantTests.cs
> -        _callFunction.Verify(call => call.SendPost(It.Is<string>(s => s == "UpdateParticipant"), It.IsAny<string>()), Times.Never());
It's not just this test method though, throughout this file there are changes being reverted that shouldn't be. Likely as the result of a merge.

2024-06-11 14:24 UTC, SamRobinson75684 commented on application/CohortManager/src/Functions/DemographicServices/DemographicDataManagementFunction/DemographicDataFunction.cs
> +        string requestBody = "";
I would agree with you but in the diagram that was drawn for us there was only one function for this function. If we want to do that we would have to speak to Steph and see if she thinks it's worth it

2024-06-11 14:37 UTC, SamRobinson75684 commented on application/CohortManager/src/Functions/Shared/Data/Database/CreateDemographicData.cs
> +            if (sqlEx.Number == 2627)
this is if we have a duplicate item added to the database, two things to bear in mind here this is just a stub of an api call and the primary key which is the recourse id in contained within the data so if we've already inserted the required data into the db we don't need to worry about it

2024-06-11 15:30 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/Functions.sln
> -Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "ScreeningValidationServiceTests", "..\..\..\..\tests\ScreeningValidationServiceTests\ScreeningValidationServiceTests.csproj", "{D4D5D8D2-B2CE-47A1
ExceptionDataService and LookupValidation are still missing in the solution file

2024-06-11 15:30 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/Shared/Model/Actions.cs
> +    public const string? Removed = "Removed";
I've taken a look at what I think it the most recent sample files and it looks like they should be "New", "Amended' and "Removed"

2024-06-11 15:37 UTC, alex-clayton-1 commented on tests/ParticipantManagementServicesTests/updateParticipantTests/updateParticipantTests.cs
> -        _callFunction.Verify(call => call.SendPost(It.Is<string>(s => s == "UpdateParticipant"), It.IsAny<string>()), Times.Never());
It still looks like it's going to revert changes that shouldn't be reverted in this file - time was spent on refactoring this. Can you copy this file from the main branch and just make the changes you need?

2024-06-12 07:13 UTC, SamRobinson75684 commented on application/CohortManager/src/Functions/Functions.sln
> -Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "ScreeningValidationServiceTests", "..\..\..\..\tests\ScreeningValidationServiceTests\ScreeningValidationServiceTests.csproj", "{D4D5D8D2-B2CE-47A1
I've added them back

2024-06-12 07:23 UTC, SamRobinson75684 commented on tests/ParticipantManagementServicesTests/updateParticipantTests/updateParticipantTests.cs
> -        _callFunction.Verify(call => call.SendPost(It.Is<string>(s => s == "UpdateParticipant"), It.IsAny<string>()), Times.Never());
they have been added back now, now, my git seems to be messing up and not pushing everything when I push

2024-06-12 08:55 UTC, Mahifernando commented
Please change title to a conventional commit type, **FEAT:** is not compliance instead it should be lower case

2024-06-12 10:03 UTC, SamRobinson75684 commented on application/CohortManager/src/Functions/DemographicServices/DemographicDataManagementFunction/DemographicDataFunction.cs
> +        string requestBody = "";
I have spoken to Steph and she has said to keep it two functions

2024-06-13 13:12 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/screeningDataServices/Properties/launchSettings.json
This Properties folder needs to be moved into the DemographicDataService folder

2024-06-13 17:27 UTC, alex-clayton-1 approved these changes

2024-06-14 07:08 UTC, merged