feat: adding a check for the use of conventional commits in pull requ…
NHSDigital/dtos-landing-zone pull request #37
Opened 2024-06-11 16:55 UTC by OllyRich1

…est titles

## Description

## Context

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-06-12 13:12 UTC, Mahifernando commented
Please provide appropriate PR description

2024-06-12 13:14 UTC, Mahifernando requested changes

2024-06-12 13:14 UTC, Mahifernando commented on .github/workflows/cicd-1-pull-request.yaml
> +  validate-title-stage:
When PR title validation failed you need to write a comment to the PR for informing an Engineer what needs to be done for correcting their PR.

If your chosen action workflow doent support direct message writing upon failure make sure you  capture PR title validation output and using another strep for writing a custom message.

2024-06-13 09:22 UTC, Mahifernando commented
Did you check PR title validation workflow on your fork?

For an example;

- Create a PR with conventional commits compliance title
- Create a PR WITHOUT conventional commits compliance title
- See if you get comments for wrong titles
- See what happens when you resolved PR title

2024-06-13 09:35 UTC, OllyRich1 commented
> Did you check PR title validation workflow on your fork?
> 
> For an example;
> 
>     * Create a PR with conventional commits compliance title
> 
>     * Create a PR WITHOUT conventional commits compliance title
> 
>     * See if you get comments for wrong titles
> 
>     * See what happens when you resolved PR title

yes, i have done all the above

2024-06-13 09:35 UTC, Mahifernando approved these changes

2024-06-13 09:35 UTC, Mahifernando approved these changes
Redy for merge 👍

2024-06-13 09:36 UTC, merged