Feature/appinsights
NHSDigital/dtos-landing-zone pull request #4
Opened 2024-04-11 07:21 UTC by MacMur85

## Description

## Context

## Type of changes

- [ ] Refactoring (non-breaking change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [x] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [x] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-04-11 11:51 UTC, Mahifernando approved these changes
Approved for merge 👍

2024-04-11 12:01 UTC, Mahifernando commented on infrastructure/modules/function-app/main.tf
> +    application_insights_key               = var.ai_key
Please remove the _**Application Insights Key**_ as it has been replaced by the connection string.

Check Azure configuration reference link [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#applicationinsights_connection_string)

2024-04-11 12:03 UTC, Mahifernando commented on infrastructure/fnapp.tf
> +  ai_key        = module.app_insights.ai_instrumentation_key
Please check previous comment and remove this 'ai_key' which is superseded by the connection string

2024-04-11 12:10 UTC, Mahifernando requested changes
Please review the comments and resolve them.

2024-04-11 12:29 UTC, MacMur85 commented on infrastructure/modules/function-app/main.tf
> +    application_insights_key               = var.ai_key
Removed from the code.

2024-04-11 12:30 UTC, MacMur85 commented on infrastructure/fnapp.tf
> +  ai_key        = module.app_insights.ai_instrumentation_key
Removed from the code

2024-04-11 12:31 UTC, MacMur85 commented
- AI Instrumentation Key removed from the config
- worker_32bit set to FALSE for all FnApps
- App Service Plan SKU increased to B3

2024-04-12 06:59 UTC, Mahifernando commented on infrastructure/sqlserver.tf
> +  fw_rule_name = var.sqlserver.fw_rule_name
Minor refactoring:

Could we convert individual variables into an object collection if this is a generic implementation? For example:

firewall_rules = [
 {name = "xxx", start_ip = "x.x.x.x", end_ip = "x.x.x.x"}
]

If we are specific on the Azure passthrough type, then something akin to this would appear more favourable:

azure_services_access_enabled = true OR false

Depending on the true or false values, the internal SQL server module can enable the '0.0.0.0' IP range for the exception.

Aditionally you could use a combination of both;

2024-04-12 08:53 UTC, MacMur85 commented on infrastructure/sqlserver.tf
> +  fw_rule_name = var.sqlserver.fw_rule_name
- sqlserver variable divided into server, dbs and fw_rules objects
- azurepassthrough parameter added to the sqlserver.server
- azurepassthrough fw rule deployed only when the var.sqlserver.server.azure_services_access_enabled variable is set to true

2024-04-12 09:51 UTC, stefaniuk reviewed
We use `_CI_AS` collation for the MSSQL server which is the default one for UK. However, this doesn't come with Unicode support. Please, can we check if this needs to be considered?

2024-04-12 10:15 UTC, MacMur85 commented
> We use `_CI_AS` collation for the MSSQL server which is the default one for UK. However, this doesn't come with Unicode support. Please, can we check if this needs to be considered?

Hi Dan! We'll reach out to data team with this one and get back to you.

2024-04-16 10:28 UTC, MacMur85 commented
> We use `_CI_AS` collation for the MSSQL server which is the default one for UK. However, this doesn't come with Unicode support. Please, can we check if this needs to be considered?

@stefaniuk, we have reached out to the Data Team for recommendations for configurations for future databases. 
This one is only a temporary one, basically created to demonstrate Function Apps capabilities in terms of importing and parsing data.

2024-04-16 11:05 UTC, Mahifernando approved these changes
Ready for merge 👍

2024-04-17 09:39 UTC, MacMur85 commented
@stefaniuk, @Mahifernando - this PR is being closed due to issues with commit verification.
New PR has been created here: https://github.com/NHSDigital/dtos-landing-zone/pull/5

2024-04-17 09:39 UTC, closed without merging