UPDATE: Now sends exception to data service and saves to new table in db
NHSDigital/dtos-landing-zone pull request #46
Opened 2024-06-17 13:19 UTC by SamRobinson75684

## Description

sends exception data to data service and saves data to database in new table

## Context

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-06-17 14:18 UTC, will-larkin-nhs requested changes

2024-06-17 14:18 UTC, will-larkin-nhs commented on tests/ScreeningValidationServiceTests/FileValidation/FileValidationTests.cs
> +    private readonly Mock<HttpWebResponse> webResponse = new();
should be `_webResponse`

2024-06-17 14:44 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/screeningDataServices/CreateValidationException/CreateValidationException.cs
The LookupValidation and StaticValidation functions call this function and pass a ValidationException, these changes will break those functions.

I think we either need a separate function for creating file validation exceptions or a db table capable of holding both types of exception.

2024-06-17 15:15 UTC, SamRobinson75684 commented on application/CohortManager/src/Functions/screeningDataServices/CreateValidationException/CreateValidationException.cs
okay so I think we can change it back for now as body of this request along with what is going to be sent is changing for everything (hence not actually writing to be db now)

2024-06-18 09:58 UTC, alex-clayton-1 submitted a review, later dismissed

2024-06-18 13:15 UTC, will-larkin-nhs submitted a review, later dismissed

2024-06-18 13:15 UTC, alex-clayton-1 commented on application/CohortManager/src/Functions/Shared/Model/FileValidationRequestBody.cs
Is this. file still needed?

2024-06-18 13:26 UTC, SamRobinson75684 commented on application/CohortManager/src/Functions/Shared/Model/FileValidationRequestBody.cs
it's not yeah, good spot. I have removed this now

2024-06-18 13:31 UTC, alex-clayton-1 approved these changes

2024-06-18 13:32 UTC, merged