feat: creating new function that will be called by other functions to allow for data aggregation
NHSDigital/dtos-landing-zone pull request #59
Opened 2024-06-24 13:17 UTC by SamRobinson75684

… for the aggregation of data

## Description

creating new function that will be called by other functions to allow for the aggregation of data

## Context

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2024-06-24 14:04 UTC, stephhou commented on application/CohortManager/src/Functions/screeningDataServices/GetValidationExceptions/GetValidationExceptions.cs
> -            _logger.LogInformation($"Exception {exception.RuleName} at {exception.DateCreated}");
Just wondering why this file has been changed.

2024-06-24 14:43 UTC, SamRobinson75684 commented on application/CohortManager/src/Functions/screeningDataServices/GetValidationExceptions/GetValidationExceptions.cs
> -            _logger.LogInformation($"Exception {exception.RuleName} at {exception.DateCreated}");
this was causing build errors as we no longer use the rule name and it's not in the model anymore

2024-06-25 06:41 UTC, will-larkin-nhs requested changes
If the application won't run without this new function, there should be a docker implementation for it

2024-06-25 06:57 UTC, will-larkin-nhs requested changes

2024-06-25 06:57 UTC, will-larkin-nhs commented on application/CohortManager/src/Functions/AggregateDataServices/AddAggregationData/AddAggregationDataFunction.cs
> +namespace AddAggregationData;
Namespace should be `NHS.CohortManager.AggregationDataServices` as per convention, and be at the top of the file as it is a file-scoped namespace

2024-06-25 06:57 UTC, will-larkin-nhs commented on application/CohortManager/src/Functions/AggregateDataServices/AddAggregationData/AddAggregationDataFunction.cs
> +public class AddAggregationDataFunction
IMO classes, functions, etc should not include noise words like "Function", not a huge issue though

2024-06-25 06:57 UTC, will-larkin-nhs commented on application/CohortManager/src/Functions/Shared/Common/Interfaces/ICreateAggregationData.cs
> +namespace Common;
namespace should be before using statements

2024-06-25 06:57 UTC, will-larkin-nhs commented on application/CohortManager/src/Functions/Shared/Data/Database/CreateAggregationData.cs
there seems to be no namespace in this file?

2024-06-25 06:57 UTC, will-larkin-nhs commented on application/CohortManager/src/Functions/Shared/Model/AggregateParticipant.cs
> +namespace Model;
namespace should be before using

2024-06-25 06:57 UTC, will-larkin-nhs commented on tests/AddAggregationDataTests/AggregationDataTests/AddAggregatonTests.cs
> +namespace AggregationDataTests;
Namespace should be `NHS.CohortManager.Tests.AddAggregationDataTests`

2024-06-25 06:57 UTC, will-larkin-nhs commented on tests/AddAggregationDataTests/AggregationDataTests/AddAggregatonTests.cs
> +        // Arrange
just have arrange here in the middle of the test. Should have arrange at the start, then act, then assert

2024-06-25 08:22 UTC, will-larkin-nhs approved these changes

2024-06-25 09:04 UTC, will-larkin-nhs approved these changes

2024-06-25 09:08 UTC, merged